### ISSUE TITLE
Разница в автоподстановке в vscode и в конвертации (вкладка Алгоритмы)

### ISSUE THREAD

**Issue by Alexei-kor** [ViktorErmakov/Conversion3.0.1#22]
На примере строк кода по созданию таблицы значений (вначале идет описание структуры ТЗ, потом добавление строки и попытка автоподстановки названия колонок таблицы). Получаем разный результат в vscode (автоподстановка отрабатывает корректно, имена колонок подставляются) и в конвертации, вкладка "Алгоритмы" (автоподстановка отрабатывает некорректно, имена колонок не подставляются)
![picture1](https://user-images.githubusercontent.com/58764863/104116821-2556a080-532d-11eb-80f1-c8cfe67364d1.png)

**Comment by ViktorErmakov** [comment]
это функционал не моей доработки а bsl_console, там не реализован пока функционал что написано в текущем коде добавлять в описание.

**Comment by Alexei-kor** [comment]
Ясно, спасибо.
