### ISSUE TITLE
Хранить настройки консоли в отдельном окне в группе Администрировании

### ISSUE THREAD

**Issue by VolAll** [ViktorErmakov/Conversion3.0.1#25]
Хранить настройки консоли в отдельном окне в группе Администрировании

больше места для кода на экране.

**Comment by ViktorErmakov** [comment]
не совсем понял Вас. Можете принскрин прислать, нарисовав там то, что Вы просите?
А где не хватает места то для кода, мешает одна командная панель с тремя кнопками?

**Comment by ViktorErmakov** [comment]
закрываю т.к. ответа нет, проблему не понял.
