### ISSUE TITLE
Алгоритмы с параметрами по умолчанию. Ошибка "Задано неправильное имя атрибута структуры"

### ISSUE THREAD

**Issue by petypen** [ViktorErmakov/Conversion3.0.1#26]
Добрый день.
Конвертации - Настройка правил конвертации - Открыть настройки правил обмена.
Перейти в режим Алгоритмы и открыть алгоритм, у которого в поле параметры есть параметры со значением по умолчанию.
Например для конвертации Бухгалтерия предприятия (3.0.91.36) таким алгоритмом будет ДобавитьПодразделениеВДопСвойства. Параметры этого алгоритма:
`ПолученныеДанные, ДанныеXDTO, ИмяПоляXDTO = "Подразделение", ИмяПоляДокумента = "ПодразделениеОрганизации"`

При разборе строки с параметрами знаки "=" и значения по умолчанию так же попадают в список имен параметров.

![2021-06-01 08-53-01 Выражение](https://user-images.githubusercontent.com/6500075/120273215-41001a80-c2bf-11eb-82f0-504c159bf323.png)
![2021-06-01 08-50-51 Скриншот экрана](https://user-images.githubusercontent.com/6500075/120273220-4198b100-c2bf-11eb-9177-9ec4493a1116.png)
![2021-06-01 08-49-55 Конвертация данных, редакция 3 1](https://user-images.githubusercontent.com/6500075/120273222-4198b100-c2bf-11eb-9e97-a2d9d32da457.png)
![2021-06-01 08-43-46 1С Предприятие](https://user-images.githubusercontent.com/6500075/120273225-42314780-c2bf-11eb-8d90-5b224e63db6b.png)

**Comment by ViktorErmakov** [comment]
Спасибо, поправлю!)

**Comment by ViktorErmakov** [comment]
Спасибо, поправлю!)

**Comment by petypen** [comment]
Спасибо за отличный продукт. Отправил PR

**Comment by ViktorErmakov** [comment]
Вам спасибо. Я думал никто не пользуется, приятно) Будем развивать дальше тогда.
