### ISSUE TITLE
Значение не является значением объектного типа getText()

### ISSUE THREAD

**Issue by MikeFilimonov** [ViktorErmakov/Conversion3.0.1#29]
![Screenshot_1](https://user-images.githubusercontent.com/3480769/124276935-1c60c200-db4d-11eb-9965-f20b39f05ee1.png)
В ПКО изменяю в обработчике ПриОтправке  код, жму "Записать" или "Записать и закрыть", получаю ошибку.

**Comment by ViktorErmakov** [comment]
Миша, можешь попробовать еще раз сымитировать, я записываю, у меня успешно, разве что когда при открытии обработчика была ошибка похожего типа, то потом и сохранить нельзя.

**Comment by ViktorErmakov** [comment]
![ЗаписьПКО](https://user-images.githubusercontent.com/39617680/126557777-b859adf2-16d1-4dec-be47-4edef2186ab1.gif)

**Comment by ViktorErmakov** [comment]
Скорее всего эта ошибка была связана с тем, что консоли еще не были готовы для работы, в новой версии страницы обработчиков не доступны, пока консоли не готовы. Ошибка не должна повториться.
