### ISSUE TITLE
КД 3.1

### ISSUE THREAD

**Issue by winnimc** [ViktorErmakov/Conversion3.0.1#34]
Не сохраняются тексты обработчиков событий  "При обработке" в справочнике "Правило обработки данных", если выбрано в правиле "Для отправки".
![image](https://user-images.githubusercontent.com/93970742/158401074-cd280135-f63c-4131-b70c-e4471d633432.png)
![image](https://user-images.githubusercontent.com/93970742/158401169-b81c67cb-179f-49fc-98d9-3bae769198e6.png)
Т.к. перед записью события при обработке сохраняются только, если выбрано "Для получения".
Пока решил так - в модуле формы ПравилаОбработкиДанных в процедуре Расш1_ПередЗаписьюПосле закомментировал условия с если:
&НаКлиенте
Процедура Расш1_ПередЗаписьюПосле(Отказ, ПараметрыЗаписи)
	
	Если КонвертацияXDTO Тогда
		
		// Запишем новый текст в реквизиты.
		//Если Объект.ИспользоватьДляПолучения Тогда
			Объект.АлгоритмПриОбработке = КонсольКодаПриОбработке.getText();
		//КонецЕсли;
		
		//Если Объект.ИспользоватьДляОтправки Тогда
			Объект.АлгоритмВыборкаДанных = КонсольКодаВыборкаДанных.getText();
		//КонецЕсли;
		
	КонецЕсли;
	
КонецПроцедуры

**Comment by ViktorErmakov** [comment]
Спасибо за замечание, можно пока и так исправить, но на самом деле там должно быть так
`Если КонвертацияXDTO Тогда
		
		// Запишем новый текст в реквизиты.
		Объект.АлгоритмПриОбработке = КонсольКодаПриОбработке.getText();
		
		Если Объект.ИспользоватьДляОтправки Тогда
			Объект.АлгоритмВыборкаДанных = КонсольКодаВыборкаДанных.getText();
		КонецЕсли;
		
	Иначе`
Скоро выпущу новую версию, там будет исправлено, заодно можно будет работать и с КД 2.0
