### ISSUE TITLE
Скачивание cfe через релизы

### ISSUE THREAD

**Issue by GenVP** [ViktorErmakov/Conversion3.0.1#4]
Само расширение cfe удобнее выкладывать через релизы. На [Releases ](https://github.com/ViktorErmakov/Conversion3.0.1/releases)- "Draft new release" и добавить описание и файл cfe. Тогда будет история версий cfe не через git.

**Comment by ViktorErmakov** [comment]
спасибо за замечание, сделаю.

**Comment by ViktorErmakov** [comment]
Выполнено, спасибо за подсказку еще раз.
