### ISSUE TITLE
Добавить поддержку базовых функций редактора кода с вызовом по горячим клавишам

### ISSUE THREAD

**Issue by MikeFilimonov** [ViktorErmakov/Conversion3.0.1#8]
Предлагаю добавить : 

1. выделение всего текста по Ctrl +A 
2. выравнивание кода по Alt+Shift +F 
3. проверку синтаксиса по Ctrl + F7

**Comment by ViktorErmakov** [comment]
1. Работает.
2 и 3 Не смогу сделать, по этому поводу нужно обращаться в проект https://github.com/salexdv/bsl_console
